log:
    tp:
        player: true
        coords: true
        here: true
        toggle: true
        back: true
        origin: true
    others:
        player: true
        coords: true
    world:
        tp: true
    jump:
        top: false
        up: false
        jump: false
    mod:
        above: true
        mass: true
        tool: true
        mover: true
    request: true
notify:
    tp:
        player: true
        coords: true
        here: true
        toggle: true
        back: true
        origin: true
    others:
        player: true
        coords: true
    world:
        tp: true
    jump:
        top: false
        up: false
        jump: false
    mod:
        above: true
        mass: true
        tool: false
        mover: false
    request: true
say:
    tp:
        player: true
        coords: true
        here: true
        toggle: true
        back: true
        origin: true
    others:
        player: true
        coords: true
    world:
        tp: true
    jump:
        top: true
        up: true
        jump: true
    mod:
        above: true
        mass: true
        tool: false
        mover: true
    request: true
disable:
    tp:
        player: false
        coords: false
        here: false
        toggle: false
        clear: false
        back: false
        origin: false
    others:
        player: false
        coords: false
    world:
        tp: false
    jump:
        top: false
        up: false
        jump: false
    mod:
        above: false
        mass: false
        tool: false
        mover: false
    request: false
glassed:
    fall-block-distance: 5
    fall-immunity: true
    fall-immunity-seconds: 5
settings:
    purge-requests-minutes: 5
    no-cross-world-tps: false
    tool-item: 288
    mover-item: 352
    page-size: 10
    client-side-glass: true
    explosion-effect: true